### PR TITLE
Allow PHPStan 0.10

### PR DESCRIPTION
**Pull request by enumag**

### CODE REVIEW

**Comment by enumag** [comment]
@ezzatron I wanted to see if the tests will pass or not but CI is failing before even starting the tests. Do you know what the error is about?

```
  [RuntimeException]                       
  github-oauth.github.com is not defined.  
```

**Comment by ezzatron** [comment]
That is weird, I'll take a look.

**Comment by ezzatron** [comment]
Okay, I had some issues with Composer config and caching in my Travis config. Could you please:

1. Rebase off of master (or merge master into your branch)
2. Run `composer update` and commit the lock file
3. Push

I tend to commit the lock file in all of my projects, and so the PR would have been building with out-of-date deps if you only committed the `composer.json` file. I should probably have an additional CI check that makes sure `composer.lock` is not out of date.

**Comment by enumag** [comment]
@ezzatron Done but the build is still failing on something similar as before.

**Comment by ezzatron** [comment]
Released in [0.2.0](https://github.com/eloquent/phpstan-phony/releases/0.2.0).

**Pull request merged**
