### PR TITLE
Enable phpstan 0.12

### PR DESCRIPTION
**Pull request by enumag**
Not sure if there are any BC breaks. Just wanna see what CI says. Maybe we'll have to drop the 0.11 support.

### CODE REVIEW

**Comment by ezzatron** [comment]
I'm working on support over in #12. There are some complex issues unfortunately. I'll need help from the PHPStan guys to solve them.

**Comment by ezzatron** [comment]
Quick update on the status of PHPStan 0.12 support. This repo is probably ready to go, and you can try it out with a `^0.7-dev` constraint (you'll also need PHPStan at `^0.12-dev` for now).

Unfortunately you'll still get a bunch of PHPStan warnings about Phony itself that look like `... no value type specified in iterable type ...`. I think this needs to be fixed by improving the PHPDoc in Phony itself, but I'm still trying to figure out the best way to do that.

**Comment by enumag** [comment]
See https://medium.com/@ondrejmirtes/generics-in-php-using-phpdocs-14e7301953 in case you didn't yet.

**Comment by ezzatron** [comment]
As of today you should find new versions of Phony with better PHPStan `0.12` compatibility . Still waiting on [this fix](https://github.com/phpstan/phpstan-src/commit/65e578c8fd8c3628aa022705ac67511846c37f17) to land in a tagged version of PHPStan, but aside from that, there shouldn't be any more major issues.

**Pull request closed without merging**
